### ISSUE TITLE
multiple cursor per snippet

### ISSUE THREAD

**Issue by markusfalk** [atom/snippets#133]
It would be awesome if I could use multiple cursor with the same ID like so:

```cson
'.source.html':
  'commented div':
    'prefix': 'div'
    'body': '<div class="$1"></div> <!-- $1 -->'
```

Thank you :)

**Comment by lee-dohm** [comment]
I just tested it with the following snippet:

```coffee
'.source.gfm':
  'Test':
    prefix: 'test'
    body: 'foo$1bar$1'
```

and it works just fine :grinning:

![multi-cursor-snippet](https://cloud.githubusercontent.com/assets/1038121/7517554/90340eae-f48a-11e4-8890-de4cb7a3c475.gif)

Is there something that isn't working for you?

**Comment by markusfalk** [comment]
The one I showed you above won't work. It only shows one cursor and leaves out the html comment. 

The result looks like this:

```html
<div class="|">

</div> 
```

First I thought this is because of emmet but I deactivated it. Same results. What information would help you to maybe have a look at the problem?

**Comment by lee-dohm** [comment]
I figured out what the problem is...

The base scope for HTML is `.text.html.basic`, not `.source.html`. You can find this information on the settings page for the language package or by executing the command "Editor: Log Cursor Scope" when your cursor is where you want the snippet to execute.

So if you use the following snippet definition:

```coffee
'.text.html.basic':
  'commented div':
    'prefix': 'div'
    'body': '<div class="$1"></div> <!-- $1 -->'
```

things should work just fine.

**Comment by markusfalk** [comment]
Thank you! :)
