### ISSUE TITLE
Tabstops do not highlight closing brackets

### ISSUE THREAD

**Issue by drew-y** [atom/snippets#164]
For example the following example:
```coffeescript
'.source.js':
  'Function':
    'prefix': 'fun'
    'body': 'function() ${1:{\n\t\n}}'
```
Should highlight the bracket block like this:
![screen shot 2015-08-18 at 3 50 56 pm](https://cloud.githubusercontent.com/assets/7987513/9343739/03261c2c-45c1-11e5-95b1-e03da039fe45.png)
But instead does not highlight the last bracket: 
![screen shot 2015-08-18 at 3 53 15 pm](https://cloud.githubusercontent.com/assets/7987513/9343787/487e7c88-45c1-11e5-8c14-d970a1f27b26.png)

This is especially problematic for the built in javascript snippet "forin".

OS: OS X 10.10.3
Atom Version: 1.0.7
Snippets Version: 0.95.0

**Comment by izuzak** [comment]
@drew-y Does this work for you? (It works for me).

```
'.source.js':
  'Function':
    'prefix': 'fun'
    'body': 'function() ${1:\\{\n\t\n\\}}'
```

See https://github.com/atom/snippets/issues/163 for a similar issue.

**Comment by drew-y** [comment]
Thanks! Is that documented anywhere?

**Comment by izuzak** [comment]
> Is that documented anywhere?

What exactly are you referring to? General escaping of special characters in template strings (`}` is obviously special since it has meaning in the template syntax) or escaping of the `}` character specifically?

**Comment by drew-y** [comment]
I mean the `}` character. It just wasn't obvious to me `\\` was necessary as the `{` is highlighted properly without escaping. I've also noticed a few packages with snippets that don't properly escape the closing bracket including the `forin` snippet from the built in language-javascript package.

**Comment by izuzak** [comment]
> I mean the } character. It just wasn't obvious to me \\ was necessary as the { is highlighted properly without escaping.

Thanks for clarifying. :bow: I'm guessing that's because of how the `{` is handled -- it's still a part of the template, but the first `}` is interpreted as the end of the template so the second `}` is just a normal string.

To answer your question -- I don't see that documented and agree it would be helpful. I think a good home for such docs would be the Flight Manual (e.g. [this section](https://atom.io/docs/latest/using-atom-snippets)), so if you'd like to open an issue (or a pull request!) over at https://github.com/atom/docs, that would be great.

> I've also noticed a few packages with snippets that don't properly escape the closing bracket including the forin snippet from the built in language-javascript package.

Ahh, thanks for pointing that out. Would you mind opening issues (or pull requests) for specific problematic snippets on the language-* issue trackers so that we can track and investigate those problems? For example, for JavaScript that would be https://github.com/atom/language-javascript.

**Comment by izuzak** [comment]
Hah, you already created that pull request: https://github.com/atom/language-javascript/pull/200 -- thank you :zap:

**Comment by drew-y** [comment]
>if you'd like to open an issue (or a pull request!) over at https://github.com/atom/docs, that would be great.

I'll do that! Thanks!
