### ISSUE TITLE
Snippets with custom numbers

### ISSUE THREAD

**Issue by azat-io** [atom/snippets#207]
How can I create a snippet which will transform something like this `w100` to this `width: 100px`?
It may be any number: `w200`, `w48`, etc.

``` json
"width": {
  "prefix": "w",
  "body": "width: ${1:${2:1}${3:px}}$0"
}
```

**Comment by savetheclocktower** [comment]
This isn’t really feasible for snippets because of how much more work it’d involve. Right now it only needs to compare the text before the cursor against a list of known prefixes. If the prefixes themselves could be dynamic, the snippets package would have to do far more work on each press of <kbd>Tab</kbd>, even presses that aren’t meant to invoke a snippet and end up inserting a literal tab character.

You could write a command that takes the content before the cursor and parses it in the way you want, inserting the result as a snippet. The only catch is that you’d probably want to assign it to a different key.

```js
atom.commands.add('atom-text-editor', {
  'custom:width-hyper-snippet': (e) => {
    let snippet = atom.packages.activePackages.snippets.mainModule;
    let editor = atom.workspace.getActiveTextEditor();
    let word = editor.getWordUnderCursor();

    let matches = word.match(/^w(\d+)/)
    if (!matches) {
      e.abortKeyBinding();
      return;
    }

    let width = matches[1];

    snippet.insert("width: ${1:${2:" + width + "}px}")
  }
});
```
