### ISSUE TITLE
Be able to not insert snippet when inside snippet

### ISSUE THREAD

**Issue by MrYurihi** [atom/snippets#237]
When using snippets, if you type in something that pulls up a snippet pop-up, there is no easy way to exit it, so if you are in a snippet, it is very annoying to not insert another snippet. There should be a 'no snippet' option on the pop-up.

**Comment by danielhickman** [comment]
Arrow keys work okay and escape works even better to keep the ability to tab through the rest of the snippet. You may be able to map the behavior to a closer button.

**Comment by savetheclocktower** [comment]
Yeah, there are several ways to fix this. One would be to change your `autocomplete-plus` settings so that the pop-up appears less often or after a longer delay. Another would be to disable the `autocomplete-snippets` package entirely so that it stops suggesting snippets as autocompletions (though this would disable them in all contexts, of course).

Either way, this is outside of our jurisdiction. Closing.
