### ISSUE TITLE
How can I disable or override the `inspect` snippet?

### ISSUE THREAD

**Issue by benpptung** [atom/snippets#240]
The snippet I hope to disable or override is:

`inspect`

It will be expanded to `console.log(require('util').inspect(, { depth: null }));`. Thank you for your help :)

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by benpptung** [comment]
Hi @Ben3eeE, 
Sorry for misunderstanding, I think this is an issue, and it can be added to 
https://github.com/atom/snippets/issues/55

There are too many unwanted snippets in `language-javascript`, and I've noticed they keep to add new snippets. It would be appreciated if we can disable unwanted snippets. Thank you.
