### ISSUE TITLE
supports regular expression?

### ISSUE THREAD

**Issue by kudou** [atom/snippets#252]
for example,I wants  the word at the beginning of the line,and
 I use ^ or \b (Backspace, e.g. in C)  or sth like it
```
'*':
  'test ':
    'prefix': 'test'
    'body': "^ echo $1| sed -n '/^[0-9]\+$/p'"
```
```
'*':
  'test ':
    'prefix': 'test'
    'body': "\b echo $1| sed -n '/^[0-9]\+$/p'"
```

they do not take effect,is there other ways ?

**Comment by savetheclocktower** [comment]
Not sure what this means. Are you saying that you want the snippet's output to start at the beginning of the line, no matter what the indentation level is when you invoke the snippet?

If so, this can't be done with a pure snippet, but could be done with a custom command which then inserts a snippet. Main drawback is that you'd have to invoke it via a keystroke rather than a snippet prefix.
