### ISSUE TITLE
<script> tag in HTML snippet 

### ISSUE THREAD

**Issue by shanemac10** [atom/snippets#263]
The snippet for <script> currently includes type="text/javascript", which generates a warning in validator.w3.org 's validation process. W3 is the world standard, and this should be addressed in the snippet.

Also, it would be nice if we could augment existing snippets, rather than building our own from scratch. From the documentation I read, I don't believe it is directly possible to do so. Thanks guys!

```
Warning: The type attribute is unnecessary for JavaScript resources.
...
<script type="text/javascript">↩     
```

**Comment by 50Wliu** [comment]
The `text/javascript` part is there so that people can easily change it to another language type when completing the snippet.  Therefore, I don't think that this will be something that we'll be changing.

> Also, it would be nice if we could augment existing snippets, rather than building our own from scratch.

Feel free to open an issue requesting this, but first please make sure an issue doesn't already exist for it.
