### ISSUE TITLE
Allow snippets to have highest priority for autocomplete suggestions

### ISSUE THREAD

**Issue by zaynv** [atom/snippets#265]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

For example, when using packages like `atom-ide-ui` and `ide-flowtype` the autocomplete suggestions from them usually show on top of the suggestions from my snippets. So when I do something like <kbd>cl</kbd>+<kbd>Tab</kbd> it autocompletes to something like `class` instead of my `console.log` snippet.

### Steps to Reproduce

Install some package that also gives you autocomplete suggestions for a language (for example, `atom-ide-ui` + an `ide-*` package, and then you can see that their suggestions will show above `snippets` suggestions.

**Expected behavior:**
Snippets suggestions should always be on top (or make this configurable at least)

**Actual behavior:**
Can't control autocomplete suggestion priority for snippets

**Reproduces how often:** 
Not sure, but it happens quite often

### Versions

```
ATOM
============
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

APM
============
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.12
git 2.10.1

OS
============
macOS High Sierra 10.13.3
```

Please let me know if I can provide any more info.

**Comment by savetheclocktower** [comment]
This feels like a band-aid for the larger problem:

1. Before the autocomplete menu appears, <kbd>Tab</kbd> expands a snippet.
2. After the autocomplete menu appears, <kbd>Tab</kbd> selects the active item in the menu.
3. The menu pops up some number of milliseconds after you stop typing, so <kbd>Tab</kbd> is liable to have changed functions in the small amount of time in between deciding to press it and pressing it.

Completion providers can specify a `suggestionPriority` to the `autocomplete-plus` package, so the concept of higher- and lower-priority providers exists. If you forked the `autocomplete-snippets` package, you could change the suggestion priority to a different number to force snippets to come first. But a better solution would be to make all the `autocomplete-*` packages (which contain the providers) expose their priority on a settings page so that they can be customized by users.

If all you care about is avoiding this single UI annoyance, I’d recommend going into the `autocomplete-plus` settings and increasing the delay before the autocomplete menu appears, or else prevent it from appearing altogether until invoked manually. Otherwise I think you should broach this topic in the `autocomplete-plus` repo to see how the maintainers feel about encouraging provider packages to make their inclusion/suggestion priorities configurable.

**Comment by savetheclocktower** [comment]
Closing this one because it's not within the scope of the snippets package (see above comment).
