### ISSUE TITLE
Project Based Snippets

### ISSUE THREAD

**Issue by FelixVicis** [atom/snippets#286]
Having project scoped snippets would be a huge help. Not all snippets that I want to add are for any file, some are only for the current project.

This was discussed in https://github.com/atom/snippets/issues/124#issuecomment-116821321 as a comment, but I think it merits its own discussion.

**Comment by rsese** [comment]
Thanks for splitting off that suggestion :+1:

We haven't updated this repository's issue templates yet but you can see from the [atom/atom template](https://raw.githubusercontent.com/atom/atom/7a9813cfe5dbf61e15e593da454f09a0b465d732/.github/ISSUE_TEMPLATE/Feature_request.md) that we're currently very unlikely to work on feature requests at the moment, especially when it's possible that a package could provide that functionality.  For example, though it doesn't seem to work with 1.34.0 (or I may have misunderstood how it works), it looks like there was a package that provided project based snippets at one point (https://atom.io/packages/modular-snippets).

So while I can definitely see how useful project based snippets could be, we're going to close this since it's not something the team would prioritize and the functionality could be provided through a package.

**Comment by FelixVicis** [comment]
Thanks for letting me know. I've tried modular snippets, but almost lost my current snippets due to a misunderstanding.
I was hoping for something more official.
