### ISSUE TITLE
Add highlighting to non-selected placeholders

### ISSUE THREAD

**Issue by edzkite** [atom/snippets#291]
## Summary

When a snippet is inserted in Atom, only the active placeholder is highlighted. Other editors, like VSCode and XCode, have fainter highlights marking the other placeholders.

## Motivation

- Today, it can be difficult for a user to know where the other placeholders are.
- Consider the linked screenshot in VSCode: We can see right away that `self` is not a placeholder but `parameter_list` is, whereas in Atom, you need to hit tab before confirming that `parameter_list` is a placeholder.
- Another pain point is inserting a snippet with exit tab stops. Without a marker, a user has no clear expectation when he or she can expect a tab stop to exit the inserted snippet.

## Describe alternatives you've considered

DIY in own package. However, such a feature could be of benefit globally across all Atom snippets consumers.

## Additional context

VSCode Snippet (Inspiration for this feature request): 
<img width="315" alt="Screen Shot 2019-06-06 at 1 19 17 PM" src="https://user-images.githubusercontent.com/47993402/59063800-badea400-885d-11e9-9d69-51c7533ab022.png">

**Comment by rsese** [comment]
Thanks for the suggestion!  Though I can see how useful this could be for some folks, as mentioned in the issue template the team is unlikely to work on new functionality right now (in general but also in particular when it's possible to take advantage of Atom's customizability or to create a package to provide the feature as you mentioned for this case).

Because of this and because we're trying to keep only tasks that need to be worked on in the issue list, I'm going to close the issue but thanks again for the feedback.
