### ISSUE TITLE
Autocomplet is not working at all for me

### ISSUE THREAD

**Issue by danyraygun** [atom/snippets#296]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by danyraygun** [comment]
I type ant type but no suggestions pop up

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by danyraygun** [comment]
What template. How do i get one?

**Comment by lkashef** [comment]
@danyraygun The same exact one you copied in your issue but it needs to be filled, so we can be able to help you better.

**Comment by savetheclocktower** [comment]
Also I'm going to mention this so as not to waste your time:

This sounds like more of a support-type question, so you may want to try the [Atom Forum](https://discuss.atom.io) first, or the Slack channel that is mentioned in the Forum's pinned topic.

If you're convinced this is a bug, I think it should first be filed in [the autocomplete-snippets repo](https://github.com/atom/autocomplete-snippets), because that's the package in charge of reporting snippet suggestions to Autocomplete+.

**Comment by danyraygun** [comment]
I just need to know how to turn on auto complete otherwise it’s gonna take
me a year to do anything
