### ISSUE TITLE
Can not add right braces '}' as content placeholder.

### ISSUE THREAD

**Issue by maschs** [atom/snippets#60]
They will break multiple things, like tabstops for example. Escaping them (`\\}`) does not solve the problem either.

**Comment by joefitzgerald** [comment]
:+1: The issue is in this code:

https://github.com/atom/snippets/blob/ce58ecf7044d4c57e128a744cc2369224d909c8d/lib/snippets.coffee#L212-L218

The regex eagerly searches for the next `}`, and does not factor in the need to count `{`'s to determine outer and inner scope. This may require something beyond regular expressions.
